return {
  "mr-u0b0dy/crazy-coverage.nvim",
  cmd = {
    "CoverageToggle",
    "CoverageToggleHitCount",
    "CoverageToggleBranchOverlay",
    "CoverageLoad",
    "CoverageNextUncovered",
    "CoveragePrevUncovered",
    "CoverageNextCovered",
    "CoveragePrevCovered",
    "CoverageNextPartial",
    "CoveragePrevPartial",
  },
  keys = {
    { "<leader>lt", "<cmd>CoverageToggle<cr>", desc = "Coverage: Toggle overlay" },
    { "<leader>lh", "<cmd>CoverageToggleHitCount<cr>", desc = "Coverage: Toggle hit count display" },
    { "<leader>lb", "<cmd>CoverageToggleBranchOverlay<cr>", desc = "Coverage: Toggle branch overlay" },
    { "]cc", "<cmd>CoverageNextCovered<cr>", desc = "Coverage: Next covered line" },
    { "[cc", "<cmd>CoveragePrevCovered<cr>", desc = "Coverage: Prev covered line" },
    { "]cp", "<cmd>CoverageNextPartial<cr>", desc = "Coverage: Next partial line" },
    { "[cp", "<cmd>CoveragePrevPartial<cr>", desc = "Coverage: Prev partial line" },
    { "]cu", "<cmd>CoverageNextUncovered<cr>", desc = "Coverage: Next uncovered line" },
    { "[cu", "<cmd>CoveragePrevUncovered<cr>", desc = "Coverage: Prev uncovered line" },
  },
  opts = {},
}
