return {
  "m4xshen/hardtime.nvim",
  event = "User AstroFile",
  opts = {
    hint_keys = {
      "k",
      "j",
      "^",
      -- "$", -- conflict with motion.leap-nvim
      "a",
      "i",
      "d",
      "y",
      "c",
      -- "l", -- conflict with motion.leap-nvim
    },
    disabled_keys = {
      "<UP>",
      "<DOWN>",
      "<LEFT>",
      "<RIGHT>",
      "<Insert>",
      "<Home>",
      "<End>",
      "<PageUp>",
      "<PageDown>",
    },
    disabled_filetypes = {
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "dapui-repl",
      "dapui_breakpoints",
      "dapui_console",
      "dapui_scopes",
      "dapui_stacks",
      "dapui_watches",
      "help",
      "lazy",
      "mason",
      "neo-tree",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
    },
  },
}
